/**
 * Tax summary report (§63). Server-rendered print-optimized HTML → user prints/saves as PDF
 * via the browser (no fabricated PDF service integration). Clearly marked as an estimate.
 */
import type { DashboardData } from '@/modules/income/service';
import { formatINR, CATEGORY_LABELS } from '@/lib/format';

export function renderTaxSummaryHtml(d: DashboardData): string {
  const calc = d.calculationNEW; // NEW regime is the default view; both are shown in comparison.
  const rows = (label: string, value: string, strong = false) =>
    `<tr><td class="${strong ? 'b' : ''}">${label}</td><td class="num ${strong ? 'b' : ''}">${value}</td></tr>`;

  const incomeRows = Object.entries(
    d.incomes.reduce<Record<string, number>>((m, i) => { m[i.category] = (m[i.category] ?? 0) + i.amount_paise; return m; }, {})
  ).map(([c, v]) => rows(CATEGORY_LABELS[c] ?? c, formatINR(v))).join('');

  const lineRows = (calc?.lines ?? []).map(l =>
    rows(`${l.description}${l.ruleId ? ` <span class="rule">${l.ruleId}</span>` : ''}`, l.taxAmount ? formatINR(l.taxAmount) : '—')).join('');

  const issues = d.reconGroups.filter(g => g.status === 'CONFLICT' || g.status === 'NEEDS_REVIEW' || g.status === 'DUPLICATE');
  const issueRows = issues.length
    ? issues.map(g => rows(`${g.category}: ${g.explanation}`, g.differencePaise ? formatINR(g.differencePaise) : '—')).join('')
    : rows('No outstanding reconciliation issues', '—');

  return `<!doctype html><html><head><meta charset="utf-8"><title>TaxOS Tax Summary</title>
<style>
 body{font-family:-apple-system,'Segoe UI',sans-serif;color:#111;max-width:720px;margin:40px auto;padding:0 24px}
 h1{letter-spacing:-0.02em} .sub{color:#6b7280;margin-top:-8px}
 table{width:100%;border-collapse:collapse;margin:16px 0}
 td{padding:8px 4px;border-bottom:1px solid #e5e7eb;font-size:14px}
 .num{text-align:right;font-variant-numeric:tabular-nums} .b{font-weight:600}
 section{margin-top:28px} h2{font-size:13px;text-transform:uppercase;letter-spacing:0.08em;color:#6b7280}
 .disclaimer{background:#fefce8;border:1px solid #fde68a;border-radius:12px;padding:14px;font-size:12px;color:#854d0e;margin-top:32px}
 .rule{color:#9ca3af;font-size:10px}
 @media print{body{margin:0}}
</style></head><body>
<h1>TaxOS Tax Summary</h1><p class="sub">FY ${d.profile?.taxYear ?? '2026-27'} · Generated ${new Date().toLocaleDateString('en-IN')}</p>
<section><h2>Snapshot</h2><table>
${rows('Total income', calc ? formatINR(calc.grossIncome) : '—')}
${rows('Taxable income', calc ? formatINR(calc.taxableIncome) : '—')}
${rows('Estimated tax (new regime)', calc ? formatINR(calc.totalTax) : '—')}
${rows('TDS / TCS / advance / self-assessment', calc ? formatINR(calc.tds + calc.tcs + calc.advanceTax + calc.selfAssessmentTax) : '—')}
${rows(calc && calc.refundOrPayable < 0 ? 'Estimated refund' : 'Estimated balance payable', calc ? formatINR(Math.abs(calc.refundOrPayable)) : '—', true)}
</table></section>
<section><h2>Income sources</h2><table>${incomeRows || rows('No income records yet', '—')}</table></section>
<section><h2>Tax calculation (every line traceable to a rule)</h2><table>${lineRows || rows('Complete your profile to generate a calculation', '—')}</table></section>
${d.comparison ? `<section><h2>Regime comparison</h2><table>
${rows('New regime total tax', formatINR(d.comparison.new.totalTax))}
${rows('Old regime total tax', formatINR(d.comparison.old.totalTax))}
${rows(`Difference (${d.comparison.difference >= 0 ? 'old is lower' : 'new is lower'})`, formatINR(Math.abs(d.comparison.difference)), true)}
</table><p style="font-size:12px;color:#6b7280">${d.comparison.explanation}</p></section>` : ''}
<section><h2>Reconciliation status</h2><table>${issueRows}</table></section>
<div class="disclaimer"><b>This is an estimate and preparation report generated by TaxOS.</b> It is not an Income Tax Department-issued document and does not constitute tax, legal or financial advice. Verify all figures against official tax records (Form 16, 26AS, AIS) before filing or making any tax payment.</div>
<script>window.print()</script>
</body></html>`;
}
